// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuCwfpQju993h6eyBz-JJgu_v8Pt5mMis',
    appId: '1:816651953206:web:0888dee3387e590fa7a497',
    messagingSenderId: '816651953206',
    projectId: 'messagerie-44b9c',
    authDomain: 'messagerie-44b9c.firebaseapp.com',
    storageBucket: 'messagerie-44b9c.appspot.com',
    measurementId: 'G-ETQ2CF9GPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvCPwiU346PsanZFn7qbDCYlyjOn8efb0',
    appId: '1:816651953206:android:84499487bd06137da7a497',
    messagingSenderId: '816651953206',
    projectId: 'messagerie-44b9c',
    storageBucket: 'messagerie-44b9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJErD6LvpScDI8YVzuC_tVpZsrM6-Uh4U',
    appId: '1:816651953206:ios:f1af61a724a62d67a7a497',
    messagingSenderId: '816651953206',
    projectId: 'messagerie-44b9c',
    storageBucket: 'messagerie-44b9c.appspot.com',
    iosClientId: '816651953206-huo5b5ne9njhordcbbpl65u885t2pf0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageriemydigitalschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJErD6LvpScDI8YVzuC_tVpZsrM6-Uh4U',
    appId: '1:816651953206:ios:f1af61a724a62d67a7a497',
    messagingSenderId: '816651953206',
    projectId: 'messagerie-44b9c',
    storageBucket: 'messagerie-44b9c.appspot.com',
    iosClientId: '816651953206-huo5b5ne9njhordcbbpl65u885t2pf0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageriemydigitalschool',
  );
}
